name: guac-tsugu
base: core24
version: '0.0.2'
summary: GBA, GBC and DS emulator written in go
description: |
   Guac is an Emulator written in golang for Gameboy, Gameboy Color, Gameboy Advance, and Nintendo DS handheld consoles.
grade: stable
confinement: strict
    
platforms:
  amd64:
  # arm64:
  #  build-on: [amd64, arm64]
  #  build-for: [arm64]

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
    
apps:
  guac-tsugu:
    command: bin/guac
    extensions: [gnome]
    environment: 
      LD_LIBRARY_PATH: $SNAP/usr/lib/guac-tsugu:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      HOME: "$SNAP_USER_DATA"
    plugs:
      - home
      - audio-playback
      - removable-media
      - unity7
      - joystick
      - alsa

parts:
  guac-tsugu:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/aabalke/guac
    source-type: git
    build-packages:
      - libx11-dev
      - libasound2-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxcursor-dev
      - libxi-dev
      - libxext-dev
      - libxkbcommon-dev
      - libxxf86vm-dev
      - libgl1-mesa-dev
      - pkg-config
    stage-packages:
      - libproxy1v5
      - libasound2
      - liboss4-salsa2
      - alsa-base
      - alsa-topology-conf
      - alsa-ucm-conf
 
   
